### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by whiz25**
This PR delivers the entire project for review.

### CODE REVIEW

**Comment by whiz25** [comment]
sorry i forgot to push my code before asking for the review. let me request for another review.

**Comment by whiz25** [comment]
thanks for the review.
i have a concern about the images on the site. these images keep changing
daily, now do you suggest i keep updating them after every review in order
to keep current? i think that would consume so much time on my side.

**Comment by JamesOkunlade** [comment]
No that's not what I meant.

**Comment by JamesOkunlade** [comment]
Images of different sections are of different size and certain label
attached to it. If you're using any image, ensure you grabbed it from that
section you want to use it so the size will fit better.

Let me know if there's anything else.

Best,

James

**Pull request merged**
